# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'VeriOnislemeQT.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

import os
import sys
from os.path import dirname, join
from PyQt5.QtWidgets import QApplication,QWidget, QFileDialog, QTableWidgetItem, QMainWindow, QMessageBox
from PyQt5.uic import loadUiType
import pandas as pd
from PyQt5 import QtCore, QtGui, QtWidgets
from sklearn import preprocessing
from sklearn.model_selection import train_test_split
from sklearn.neighbors import LocalOutlierFactor
import numpy as np



class Ui_Dialog(QtWidgets.QMainWindow):

    def openFile(self):
        path = QFileDialog.getOpenFileName(self, 'Open CSV', os.getenv('HOME'), 'CSV(*.csv)')
        oku = pd.read_csv(path[0])
        self.all_data = oku.copy()
        self.all_data = self.all_data.dropna()
        self.showData()
        self.oznitelikDoldur()

    def aykiriBaskilama(self):
        clf = LocalOutlierFactor(n_neighbors=20, contamination=0.1)
        clf.fit_predict(self.X)
        df_scores = clf.negative_outlier_factor_
        esik = np.sort(df_scores)[13]
        aykiri = df_scores > esik
        yeni = self.X[df_scores > esik]
        baski = self.X[df_scores == esik]
        aykirilar = self.X[~aykiri]

        res = aykirilar.to_records(index=False)
        res[:] = baski.to_records(index=False)
        self.X[~aykiri] = pd.DataFrame(res, index=self.X[~aykiri].index)


    def showData(self):
        try:
            numRows = self.all_data.shape[0]
            self.tableWidget.setColumnCount(len(self.all_data.columns))
            self.tableWidget.setRowCount(numRows)
            self.tableWidget.setHorizontalHeaderLabels(self.all_data.columns)

            for i in range(len(self.all_data.columns)):
                for j in range(numRows):
                    self.tableWidget.setItem(j, i, QTableWidgetItem(str(self.all_data.iat[j, i])))

            self.tableWidget.resizeColumnsToContents()
        except Exception as a:
            print(a)

    def oznitelikDoldur(self):
        self.HedefOznitelik.clear()
        for i in self.all_data.columns:
            self.HedefOznitelik.addItem(i)
    def oznitelikSec(self):
        hedef = self.HedefOznitelik.currentText()
        self.y = self.all_data[hedef]
        self.X = self.all_data.drop([hedef], axis=1)
        self.X = pd.get_dummies(self.X)
        self.aykiriBaskilama()
        QMessageBox.about(self, "Hedef Öznitelik", hedef)

    def islemler(self):
        if self.StandartizasyonRadioButton.isChecked() == True:
            self.X = preprocessing.scale(self.X)
            QMessageBox.about(self, "İşlem", "Standartizasyon Tamamlandı")
        elif self.NormalizasyonRadio.isChecked() == True:
            self.X = preprocessing.normalize(self.X)
            QMessageBox.about(self, "İşlem", "Normalizasyon Tamamlandı")
        elif self.MinMaxRadio.isChecked() == True:
            self.X = preprocessing.MinMaxScaler(self.X)
            QMessageBox.about(self, "İşlem", "MinMax Scale Tamamlandı")

    def trainSpotting(self):
        self.X_train, self.X_test, self.y_train, self.y_test = train_test_split(self.X, self.y, test_size=self.TestSizeBox.value(), random_state=self.RandomStateBox.value())
        QMessageBox.about(self, "İşlem", str(self.TestSizeBox.value()) + "ve" + str((1 - self.TestSizeBox.value())) + "Hold Out Kullanarak Ayrılmıştır.")

    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(775, 409)
        self.tabWidget = QtWidgets.QTabWidget(Dialog)
        self.tabWidget.setGeometry(QtCore.QRect(0, 0, 971, 581))
        self.tabWidget.setObjectName("tabWidget")
        self.VeriOnislemeTab = QtWidgets.QWidget()
        self.VeriOnislemeTab.setObjectName("VeriOnislemeTab")
        self.VeriSecButton = QtWidgets.QPushButton(self.VeriOnislemeTab)
        self.VeriSecButton.setGeometry(QtCore.QRect(10, 30, 91, 41))
        self.VeriSecButton.setObjectName("VeriSecButton")
        self.StandartGrup = QtWidgets.QGroupBox(self.VeriOnislemeTab)
        self.StandartGrup.setGeometry(QtCore.QRect(280, 10, 221, 81))
        self.StandartGrup.setTitle("")
        self.StandartGrup.setObjectName("StandartGrup")
        self.StandartizasyonRadioButton = QtWidgets.QRadioButton(self.StandartGrup)
        self.StandartizasyonRadioButton.setGeometry(QtCore.QRect(20, 10, 101, 17))
        self.StandartizasyonRadioButton.setObjectName("StandartizasyonRadioButton")
        self.NormalizasyonRadio = QtWidgets.QRadioButton(self.StandartGrup)
        self.NormalizasyonRadio.setGeometry(QtCore.QRect(20, 30, 101, 17))
        self.NormalizasyonRadio.setObjectName("NormalizasyonRadio")
        self.MinMaxRadio = QtWidgets.QRadioButton(self.StandartGrup)
        self.MinMaxRadio.setGeometry(QtCore.QRect(20, 50, 131, 17))
        self.MinMaxRadio.setObjectName("MinMaxRadio")
        self.StandartButton = QtWidgets.QPushButton(self.StandartGrup)
        self.StandartButton.setGeometry(QtCore.QRect(160, 20, 51, 41))
        self.StandartButton.setObjectName("StandartButton")
        self.TestGrup = QtWidgets.QGroupBox(self.VeriOnislemeTab)
        self.TestGrup.setGeometry(QtCore.QRect(510, 10, 241, 80))
        self.TestGrup.setTitle("")
        self.TestGrup.setObjectName("TestGrup")
        self.RandomStateBox = QtWidgets.QSpinBox(self.TestGrup)
        self.RandomStateBox.setGeometry(QtCore.QRect(100, 20, 61, 22))
        self.RandomStateBox.setObjectName("RandomStateBox")
        self.TestSizeBox = QtWidgets.QDoubleSpinBox(self.TestGrup)
        self.TestSizeBox.setGeometry(QtCore.QRect(100, 50, 62, 22))
        self.TestSizeBox.setMinimum(0.1)
        self.TestSizeBox.setMaximum(1.0)
        self.TestSizeBox.setObjectName("TestSizeBox")
        self.label_2 = QtWidgets.QLabel(self.TestGrup)
        self.label_2.setGeometry(QtCore.QRect(10, 20, 81, 16))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.TestGrup)
        self.label_3.setGeometry(QtCore.QRect(10, 50, 47, 13))
        self.label_3.setObjectName("label_3")
        self.TestSizeButton = QtWidgets.QPushButton(self.TestGrup)
        self.TestSizeButton.setGeometry(QtCore.QRect(170, 20, 51, 41))
        self.TestSizeButton.setObjectName("TestSizeButton")
        self.tableWidget = QtWidgets.QTableWidget(self.VeriOnislemeTab)
        self.tableWidget.setGeometry(QtCore.QRect(0, 110, 771, 271))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.HedefGroup = QtWidgets.QGroupBox(self.VeriOnislemeTab)
        self.HedefGroup.setGeometry(QtCore.QRect(120, 10, 151, 81))
        self.HedefGroup.setTitle("")
        self.HedefGroup.setObjectName("HedefGroup")
        self.HedefOznitelik = QtWidgets.QComboBox(self.HedefGroup)
        self.HedefOznitelik.setGeometry(QtCore.QRect(20, 30, 111, 22))
        self.HedefOznitelik.setObjectName("HedefOznitelik")
        self.label = QtWidgets.QLabel(self.HedefGroup)
        self.label.setGeometry(QtCore.QRect(20, 10, 121, 16))
        self.label.setObjectName("label")
        self.pushButton = QtWidgets.QPushButton(self.HedefGroup)
        self.pushButton.setGeometry(QtCore.QRect(40, 55, 75, 21))
        self.pushButton.setObjectName("pushButton")
        self.tabWidget.addTab(self.VeriOnislemeTab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.tabWidget.addTab(self.tab_2, "")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)








    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.VeriSecButton.setText(_translate("Dialog", "Veri Seti Seç"))
        self.StandartizasyonRadioButton.setText(_translate("Dialog", "Standartizasyon"))
        self.NormalizasyonRadio.setText(_translate("Dialog", "Normalizasyon"))
        self.MinMaxRadio.setText(_translate("Dialog", "MinMax Normalizasyon"))
        self.StandartButton.setText(_translate("Dialog", "Seç"))
        self.label_2.setText(_translate("Dialog", "Random State"))
        self.label_3.setText(_translate("Dialog", "Test Size"))
        self.TestSizeButton.setText(_translate("Dialog", "Seç"))
        self.label.setText(_translate("Dialog", "Hedef Özniteliği Seçiniz."))
        self.pushButton.setText(_translate("Dialog", "Seç"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.VeriOnislemeTab), _translate("Dialog", "Veri Önişleme"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("Dialog", "Tab 2"))

        self.VeriSecButton.clicked.connect(self.openFile)
        self.pushButton.clicked.connect(self.oznitelikSec)
        self.StandartButton.clicked.connect(self.islemler)
        self.TestSizeButton.clicked.connect(self.trainSpotting)

